### ISSUE TITLE
How to start container

### ISSUE THREAD

**Issue by RPS98** [roboticswithjulia/ros2_rust_workshop#1]
Después de compilar la imagen con:

```
cd ~/ros2_rust_ws/src/rust_ws_docs/.docker
./build_image.sh
```

Muestras el start del contenedor mediante:

https://github.com/roboticswithjulia/ros2_rust_workshop/blob/9747eb1ee67dd2689840098fc8b1219cada88d3d/ROS2%20Rust%20workshop.ipynb#L325

¿Pero cuál es la forma correcta de levantar dicho contenedor?
En VSCode me sale la imagen `ros2_rust_dev:latest` pero ningún `Containers`. Si inicio un contenedor con dicha imagen, dentro no tiene `~/ros2_rust_ws/`. Entonces entiendo que hay que o clonarlo o montarlo al levantar el contenedor, para poder hace el último paso:

```
sudo apt-get update
rosdep install --from-paths ~/ros2_rust_ws/src --ignore-src -r -y
source /opt/ros/humble/setup.sh
colcon build
```

**Comment by roboticswithjulia** [comment]
Hola Rafa,
Muchas gracias por probar el setup.
Si, creo que hay un error. 
1.  Puedes parar la imagen anterior (Stop en la pestaña de containers),  Todos los containers deberían salir parados(con un cuadradito rojo).
2. En una  nueva terminal dentro de vscode o terminal local  ejecutar  `cd  ~/ros2_rust_ws/src/ros2_rust_workshop` y luego `.docker/run_user.sh`
3. Abrir vscode, ir a las imagenes de docker (igual que has echo anteriormente), te saldrá una creada hace pocos minutos, activarla (botón derecho->start) y tendria que ponerse en play (triangulo verde) botón derecho y attach vscode.
4. Te debería funcionar. Cualquer cosa me dices. Gracias!

**Comment by roboticswithjulia** [comment]
Hablé con Rafa durante la ROSConEs y me informó que el paso anterior le funcionó. Voy a cerrar la issue :)
