### ISSUE TITLE
Devcontainer con user instrucciones

### ISSUE THREAD

**Issue by awesomebytes** [roboticswithjulia/ros2_rust_workshop#2]
Necesitarias anyadir algo como:

```Dockerfile
ARG CONTAINER_USER="cuser"
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create a user in the container to operate as unprivileged
RUN groupadd --gid $USER_GID $CONTAINER_USER \
    && useradd --uid $USER_UID --gid $USER_GID -m $CONTAINER_USER \
    && mkdir -p /home/$CONTAINER_USER
RUN apt-get update \
    && apt-get install -y sudo \
    && rm -rf /var/lib/apt/lists/* \
    && echo $CONTAINER_USER ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$CONTAINER_USER \
    && chmod 0440 /etc/sudoers.d/$CONTAINER_USER
```

No es necesario pero yo suelo pasar a usar bash en el Docker/Dockerfile:
```Dockerfile
# Use to get a shell with color support and additional bashrc goodies
SHELL ["/bin/bash", "--login", "-c"]
```

En el devcontainer.json:
```json
	"remoteUser": "cuser",

```

No es necesario pero yo suelo forzar:
```json
	"containerEnv": {
		// Convenience, for shell colors, aliases, etc
		"SHELL": "/bin/bash"
    },
```

Luego el tema es instalar cargo, y cualquier cosa de usuario final, con el user hecho antes, por ejemplo, para usar `uv` yo tengo en Dockerfile:
```Dockerfile
# Install uv
ARG VENV_NAME=vpy3.12
USER $CONTAINER_USER
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/home/${CONTAINER_USER}/.cargo/bin:$PATH"
# Create a system venv to use from now on
RUN uv venv /home/${CONTAINER_USER}/$VENV_NAME -p 3.12
# Use the virtual environment automatically
ENV VIRTUAL_ENV=/home/${CONTAINER_USER}/$VENV_NAME
# Place entry points in the environment at the front of the path
ENV PATH="/home/${CONTAINER_USER}/$VENV_NAME/bin:$PATH"
RUN uv python install 3.12
# Tooling + necessary to run rospy
RUN uv pip install ipython rospkg empy
```

**Comment by Ahmed-khalil3** [comment]
I think this will help you.
https://bit.ly/3TyLBMS

you may need to install the c compiler

**Comment by roboticswithjulia** [comment]
Hola @awesomebytes,
Quería agradecerte la gran ayuda durante el workshop y también estos comentarios.
He aplicado los cambios tal y como has indicado, esta tarde voy a volver a probar todo el workshop, aunque ahora debería funcionar todo correctamente.

Un saludo y gracias por la gran ayuda!

**Comment by awesomebytes** [comment]
Genial!
Let me know si hay algo mas en lo que pueda ayudar :)

**Comment by roboticswithjulia** [comment]
Hola @awesomebytes, he intentado compilar todo pero parece que es necesario utilizar un usuario con permisos de root para instalar Rust en ROS2 o bien, puede que algún parametro de  https://github.com/roboticswithjulia/ros2_rust_workshop/blob/develop/.docker/run_user.sh no sea el correcto:

```
cuser@jmr:~/ros2_rust_ws$ colcon build
[0.200s] WARNING:colcon.colcon_core.verb:No task extension to 'build' a 'ros.ament_cargo' package
[0.206s] WARNING:colcon.colcon_core.verb:No task extension to 'build' a 'ros.ament_cargo' package
[0.207s] WARNING:colcon.colcon_core.verb:No task extension to 'build' a 'ros.ament_cargo' package
[0.207s] WARNING:colcon.colcon_core.verb:No task extension to 'build' a 'ros.ament_cargo' package
[0.207s] WARNING:colcon.colcon_core.verb:No task extension to 'build' a 'ros.ament_cargo' package
[0.207s] WARNING:colcon.colcon_core.verb:No task extension to 'build' a 'ros.ament_cargo' package
Starting >>> rosidl_generator_rs
[0.215s] ERROR:colcon.colcon_cmake.task.cmake.build:Failed to find the following files:
- /home/cuser/ros2_rust_ws/install/rosidl_runtime_rs/share/rosidl_runtime_rs/package.sh
Check that the following packages have been built:
- rosidl_runtime_rs
Failed   <<< rosidl_generator_rs [0.01s, exited with code 1]
Starting >>> champ
Starting >>> champ_description
Starting >>> test_interface_files
Starting >>> champ_config
Starting >>> champ_navigation
[0.233s] WARNING:asyncio:Unknown child process pid 1035, will report returncode 255
Aborted  <<< champ [0.01s]
Aborted  <<< champ_description [0.01s]
Aborted  <<< test_interface_files [0.01s]
Aborted  <<< champ_config [0.01s]
Aborted  <<< champ_navigation [0.00s]

Summary: 0 packages finished [0.18s]
  1 package failed: rosidl_generator_rs
  5 packages aborted: champ champ_config champ_description champ_navigation test_interface_files
  30 packages not processed
```

He creado otra branch `develop` dónde puedes encontrar estos cambios y he dejado `main` con la configuración del dia del workshop.
He estado mirando otros casos parecidos cómo este: https://github.com/ros2-rust/ros2_rust/issues/397, he probado de usar colcon build  --merge-install pero sin éxito. 

Saludos y gracias,

Júlia

**Comment by awesomebytes** [comment]
Hola,

He hecho un PR: https://github.com/roboticswithjulia/ros2_rust_workshop/pull/3

Para usar devcontainer. Veras que no uso ninguno de esos scripts... asi que no se si es lo que querrias. Implica soportar 2 formas de hacer el workshop 1. Docker directamente 2. Devcontainers (e incluso 3. directamente en el host).

Pero igual alguna cosa que hago alli te ayuda.

**Comment by roboticswithjulia** [comment]
Gracias @awesomebytes por el PR, y por tus comentarios, no tengo ninguna duda que son la excelencia de este workshop! 
Voy a realizar los cambios respectivos y en cuanto esté todo funcionando haré un merge a main.  

Gracias por todo!!

**Comment by awesomebytes** [comment]
Un placer, solo son detalles para el trabajo que has creado :)

Ya te haré ping, no lo dudes!
